# Generated by Django 5.2.5 on 2025-08-21 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDefaultCoeff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOLID', '고체'), ('LIQUID', '액체'), ('GAS', '기체')], max_length=10, unique=True)),
                ('default_emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('default_calorific_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gross_area', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('conditioned_area', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('heating_area', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cooling_area', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_infos', to='buildings.building')),
            ],
            options={
                'unique_together': {('building', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ElectricityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_kwh', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_usages', to='buildings.building')),
            ],
            options={
                'unique_together': {('building', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Scope1FuelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('SOLID', '고체'), ('LIQUID', '액체'), ('GAS', '기체')], max_length=10)),
                ('tier', models.IntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3')])),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=10)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('calorific_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope1_usages', to='buildings.building')),
            ],
            options={
                'unique_together': {('building', 'year', 'category')},
            },
        ),
    ]
