# Generated by Django 5.2.5 on 2025-08-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areainfo',
            name='cooling_area',
        ),
        migrations.RemoveField(
            model_name='areainfo',
            name='heating_area',
        ),
    ]
