# Generated by Django 5.2.5 on 2025-08-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('scope1_solid_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scope1_liquid_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scope1_gas_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scope1_total_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scope2_elec_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_kg', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('area_m2', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('i_solid', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('i_liquid', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('i_gas', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('i_elec', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('i_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_aggs', to='buildings.building')),
            ],
            options={
                'unique_together': {('building', 'year')},
            },
        ),
    ]
