# Generated by Django 5.2.5 on 2025-08-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('usage', models.CharField(choices=[('OFFICE', '업무 시설'), ('EDU_RESEARCH', '교육 연구 시설'), ('CULTURE_ASSEMBLY', '문화 및 집회시설'), ('MEDICAL', '의료 시설'), ('TRAINING', '수련 시설'), ('TRANSPORT', '운수 시설')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(choices=[('KAKAO', '카카오'), ('NAVER', '네이버'), ('GOOGLE', '구글'), ('OTHER', '기타/없음')], default='OTHER', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buildings', to='accounts.account')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='accounts.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'name'], name='buildings_b_institu_3a3837_idx'), models.Index(fields=['institution', 'place_id'], name='buildings_b_institu_33f52c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False), models.Q(('place_id', ''), _negated=True)), fields=('institution', 'place_id'), name='uq_building_place_per_institution_active'), models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('institution', 'name'), name='uq_building_name_per_institution_active')],
            },
        ),
    ]
